### ISSUE TITLE
I got "No such file or directory" error

### ISSUE THREAD

**Issue by hossammourad** [front-cli/front-cli#1]
Hi,

I wanted to try out the tool but after I installed it globally with no errors, this error happened when I use the "front" command:

`/usr/bin/env: ‘node\r’: No such file or directory`

Thanks.

**Comment by victorwpbastos** [comment]
What OS and version are you using?

**Comment by hossammourad** [comment]
@victorwpbastos Ubuntu 16.04

**Comment by victorwpbastos** [comment]
Maybe you should try install with sudo?

**Comment by hossammourad** [comment]
@victorwpbastos This is what I did.

**Comment by victorwpbastos** [comment]
It was a problem with VS Code line endings. The new version should work! Closing the issue, if the problem persists please reopen.
